### ISSUE TITLE
Error with Svelte 5.0.0

### ISSUE THREAD

**Issue by tuemaytinh1981** [themesberg/flowbite-svelte#1185]
### Describe the bug

✘ [ERROR] No matching export in "node_modules/.pnpm/svelte@5.0.0-next.26/node_modules/svelte/src/internal/index.js" for import "get_current_component"

    node_modules/.pnpm/flowbite-svelte@0.44.20_svelte@5.0.0-next.26/node_modules/flowbite-svelte/dist/utils/createEventDispatcher.js:9:9:
      9 │ import { get_current_component } from 'svelte/internal';
        ╵          ~~~~~~~~~~~~~~~~~~~~~

10:43:53 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.pnpm/flowbite-svelte@0.44.20_svelte@5.0.0-next.26/node_modules/flowbite-svelte/dist/utils/createEventDispatcher.js:9:9: ERROR: No matching export in "node_modules/.pnpm/svelte@5.0.0-next.26/node_modules/svelte/src/internal/index.js" for import "get_current_component"
    at failureErrorWithLog (/Users/maitrongtue/Documents/GitHub/odm/node_modules/.pnpm/esbuild@0.19.9/node_modules/esbuild/lib/main.js:1650:15)
    at /Users/maitrongtue/Documents/GitHub/odm/node_modules/.pnpm/esbuild@0.19.9/node_modules/esbuild/lib/main.js:1058:25
    at /Users/maitrongtue/Documents/GitHub/odm/node_modules/.pnpm/esbuild@0.19.9/node_modules/esbuild/lib/main.js:1526:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Reproduction

<script>
  import { Button } from 'flowbite-svelte';
</script>
<Button>Default</Button>
<Button color="alternative">Alternative</Button>

### Flowbite version and System Info

```shell
Svelte 5.0.0
```

**Comment by shinokada** [comment]
"peerDependencies": {
    "svelte": "^4.0.0"
  },

**Comment by tuemaytinh1981** [comment]
I thinks error in function utils/createEventDispatcher.js: import "get_current_component"... May be big change event function on Svelte 5.0.0.

**Comment by jjagielka** [comment]
This problem is already addressed with PR #1168 
It needs the official tag though.

**Comment by jjagielka** [comment]
@tuemaytinh1981 new version is released now. Can you please check if issue is corrected?

**Comment by GreenDiscord** [comment]
> @tuemaytinh1981 new version is released now. Can you please check if issue is corrected?

I still get this issue @jjagielka , It wont let me install unless I have v4 installed, which doesn't have some features I'm using.

**Comment by jjagielka** [comment]
@GreenDiscord the line `import { get_current_component } from 'svelte/internal';` does not exist any more in the code base.
Can you please give the details what is blocking you?

**Comment by shinokada** [comment]
Please use v1.x.x.
