### ISSUE TITLE
Datepicker bug when inside modal.

### ISSUE THREAD

**Issue by speedwheel** [themesberg/flowbite-svelte#1479]
### Describe the bug

When I put the calendar inside a Flowbite modal,  the dropdown opens inside the modal instead of on top of the modal, and I've managed to fix more or less  by  applying `position:fixed`  on the dropdown menu, but the positioning is not dynamic anymore.

### Reproduction

Insert a datepicker component inside a Flowbite component and try to open the datepicker dropdown.

```
<Modal
	title="Add task"
	outsideclose
	size="md">
<Datepicker
bind:value={modalDataPanelDate}
dateFormat={{ year: '2-digit', month: 'short', day: '2-digit' }}
defaultDate={new Date()}
autohide={false}
showActionButtons
/>
</Modal>
```

### Flowbite version and System Info

```shell
"svelte": "^5.0.0"
"flowbite": "^2.5.2",
"flowbite-svelte": "^0.47.2",

Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
```
<img width="548" alt="image" src="https://github.com/user-attachments/assets/222a4538-988a-4768-ab2e-e4c427696969">

**Comment by adrianet86** [comment]
Having similar issue.
The DatePicker does not show up.

<img width="1010" alt="image" src="https://github.com/user-attachments/assets/1de937a3-f0f1-4fa3-9273-ecae30e778d7">

Here my version of dependencies.

"svelte": "^4.2.19",
"flowbite": "^2.5.2",
"flowbite-svelte": "^0.44.24",

**Comment by KiraPC** [comment]
Any updates on this?

**Comment by thebiglabasky** [comment]
Same here. That's due to hardcoding `z-10` [here](https://github.com/themesberg/flowbite-svelte/blob/2e81484b964a6a45806fcface52fd7a743f6324a/src/lib/datepicker/Datepicker.svelte#L270)
There is also no way to override that easily.
I'll try figuring a way out using some CSS wizardry but that's far from ideal.

**Comment by shinokada** [comment]
v1 should fix this.

**Comment by idesignzone** [comment]
"flowbite": "^3.1.2",

and this problem still not solved.
Can't get the datepicker to open above the modal.

datepicker is placed under the body tag. is there any way to change this behaviour?

**Comment by jjagielka** [comment]
Try to add `class="fixed"` to the `Datepicker`

**Comment by idesignzone** [comment]
> Try to add `class="fixed"` to the `Datepicker`

the only way I could fix this was by changing the default container.

```
datepickerInstance = new Datepicker(datepickerInput.value, {
    container: '#datepicker-container',
  });
```

**Comment by jjagielka** [comment]
That works for me:
```svelte
<Modal open={true} title="Title">
  <Datepicker class="fixed" />
</Modal>
```
Datepicker dropdown is on top.
