### ISSUE TITLE
classUl prop for Dropdown does nothing

### ISSUE THREAD

**Issue by jeremypeters** [themesberg/flowbite-svelte#908]
### Describe the bug

Values given in the classUl prop for the Dropdown have no effect. Also if a value is added to the Dropdown class prop it is applied to both the Dropdown div and the ul.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-saxuae?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info

```shell
See Stackblitz reproduction.
```

**Comment by jjagielka** [comment]
Fixed in PR #912

**Comment by ankified** [comment]
Hi, I'm using flowbite-svelte@0.44.19 and this issue persists. Can you please check on it?
![image](https://github.com/themesberg/flowbite-svelte/assets/75060185/5af21e16-92a6-404e-924d-16f935806c5f)

**Comment by jjagielka** [comment]
`classUI` property does not exist in `Dropdown` component - docs need to be updated.

You can control the `<ul>` element of the `Dropdown` by setting directly `class` property.
```svetle
<Dropdown ... class='py-0'>
```

**Comment by ankified** [comment]
Thank you. It worked!
